namespace PCCheck;
public sealed class SettingsForm:Form
{
 readonly TextBox device=new(),sender=new(),recipient=new(),password=new();readonly ComboBox provider=new();readonly DateTimePicker time=new();readonly NumericUpDown idle=new();readonly CheckBox startMail=new(),summary=new(),autoStart=new();readonly AppSettings current;
 public SettingsForm(AppSettings s){current=s;Text="PC Check 설정";Size=new Size(520,610);StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;Font=new Font("맑은 고딕",10);Build();LoadValues();}
 void Build(){var y=25;Controls.Add(new Label{Text="메일 및 기록 설정",Font=new Font("맑은 고딕",18,FontStyle.Bold),Location=new Point(28,y),AutoSize=true});y+=58;AddRow("PC 이름",device,y);y+=45;provider.DropDownStyle=ComboBoxStyle.DropDownList;provider.Items.AddRange(["Gmail","네이버"]);AddRow("메일 종류",provider,y);y+=45;AddRow("보내는 주소",sender,y);y+=45;AddRow("받는 주소",recipient,y);y+=45;password.UseSystemPasswordChar=true;AddRow("앱 비밀번호",password,y);y+=45;time.Format=DateTimePickerFormat.Time;time.ShowUpDown=true;AddRow("요약 시각",time,y);y+=45;idle.Minimum=1;idle.Maximum=30;AddRow("자리 비움 기준",idle,y);y+=48;startMail.Text="PC 시작·종료 메일 보내기";startMail.Location=new Point(175,y);startMail.AutoSize=true;Controls.Add(startMail);y+=34;summary.Text="매일 요약 메일 보내기";summary.Location=new Point(175,y);summary.AutoSize=true;Controls.Add(summary);y+=34;autoStart.Text="Windows 로그인 시 자동 실행";autoStart.Location=new Point(175,y);autoStart.AutoSize=true;Controls.Add(autoStart);y+=48;var test=new Button{Text="테스트 메일",Location=new Point(28,y),Size=new Size(140,38)};test.Click+=async(s,e)=>await Test();Controls.Add(test);var save=new Button{Text="저장",Location=new Point(180,y),Size=new Size(290,38),BackColor=Color.FromArgb(42,116,245),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};save.Click+=(s,e)=>Save();Controls.Add(save);}
 void AddRow(string label,Control control,int y){Controls.Add(new Label{Text=label,Location=new Point(30,y+5),Size=new Size(135,25)});control.Location=new Point(175,y);control.Size=new Size(295,28);Controls.Add(control);}
 void LoadValues(){device.Text=current.DeviceName;provider.SelectedItem=current.Provider;sender.Text=current.Sender;recipient.Text=current.Recipient;password.Text=SecretProtector.Unprotect(current.ProtectedPassword);if(TimeSpan.TryParse(current.SummaryTime,out var t))time.Value=DateTime.Today.Add(t);idle.Value=current.IdleMinutes;startMail.Checked=current.SendStartMail;summary.Checked=current.SendDailySummary;autoStart.Checked=AppSettings.IsAutoStart();}
 AppSettings FormSettings()=>new(){DeviceName=device.Text.Trim(),Provider=provider.Text,Sender=sender.Text.Trim(),Recipient=recipient.Text.Trim(),ProtectedPassword=SecretProtector.Protect(password.Text),SummaryTime=time.Value.ToString("HH:mm"),IdleMinutes=(int)idle.Value,SendStartMail=startMail.Checked,SendDailySummary=summary.Checked};
 async Task Test(){try{var s=FormSettings();await MailService.Send(s,$"[{s.DeviceName}] 테스트 메일",$"PC Check 메일 연결이 정상입니다.\r\n{DateTime.Now:yyyy-MM-dd HH:mm:ss}");MessageBox.Show("테스트 메일을 보냈습니다.","PC Check");}catch(Exception ex){MessageBox.Show("메일 발송 실패\r\n"+ex.Message,"PC Check");}}
 void Save(){if(string.IsNullOrWhiteSpace(device.Text)){MessageBox.Show("PC 이름을 입력해주세요.");return;}FormSettings().Save();AppSettings.SetAutoStart(autoStart.Checked);DialogResult=DialogResult.OK;Close();}
}
