namespace PCCheck;
public sealed class SettingsForm:Form
{
 readonly AppSettings settings;readonly NumericUpDown idle=new();readonly TextBox newPass=new(),confirm=new();
 public SettingsForm(AppSettings s){settings=s;if(!ParentSecurity.Ask(this,s,"관리 설정 열기")){Shown+=(a,b)=>Close();return;}Text="PC Check 관리 설정";Size=new Size(650,630);StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;Font=new Font("맑은 고딕",12);Build();}
 void Build(){Controls.Add(new Label{Text="관리 설정",Location=new Point(35,26),AutoSize=true,Font=new Font("맑은 고딕",24,FontStyle.Bold)});Controls.Add(new Label{Text="PC 시작 시 자동 실행은 항상 켜져 있습니다.",Location=new Point(38,78),AutoSize=true,ForeColor=Color.FromArgb(28,155,103),Font=new Font("맑은 고딕",13,FontStyle.Bold)});var card=new Panel{Location=new Point(35,125),Size=new Size(565,130),BackColor=Color.FromArgb(245,247,251)};Controls.Add(card);card.Controls.Add(new Label{Text="자리 비움 판단 시간",Location=new Point(24,22),AutoSize=true,Font=new Font("맑은 고딕",15,FontStyle.Bold)});card.Controls.Add(new Label{Text="이 시간 동안 입력이 없으면 사용시간에서 제외합니다.",Location=new Point(24,58),AutoSize=true,ForeColor=Color.DimGray});idle.Location=new Point(420,38);idle.Size=new Size(100,35);idle.Minimum=1;idle.Maximum=30;idle.Value=settings.IdleMinutes;idle.Font=new Font("맑은 고딕",14);card.Controls.Add(idle);card.Controls.Add(new Label{Text="분",Location=new Point(525,45),AutoSize=true});Controls.Add(new Label{Text="부모 비밀번호 변경",Location=new Point(38,285),AutoSize=true,Font=new Font("맑은 고딕",16,FontStyle.Bold)});AddRow("새 비밀번호",newPass,330);AddRow("한 번 더 입력",confirm,385);var save=new Button{Text="설정 저장",Location=new Point(35,465),Size=new Size(270,50),BackColor=Color.FromArgb(42,116,245),ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Font=new Font("맑은 고딕",13,FontStyle.Bold)};save.Click+=(s,e)=>Save();Controls.Add(save);var del=new Button{Text="모든 사용 기록 삭제",Location=new Point(325,465),Size=new Size(275,50),BackColor=Color.White,ForeColor=Color.Firebrick,FlatStyle=FlatStyle.Flat,Font=new Font("맑은 고딕",13,FontStyle.Bold)};del.Click+=(s,e)=>DeleteData();Controls.Add(del);var uninstall=new Button{Text="PC Check 프로그램 제거",Location=new Point(35,530),Size=new Size(565,45),BackColor=Color.White,ForeColor=Color.Firebrick,FlatStyle=FlatStyle.Flat};uninstall.Click+=(s,e)=>Uninstall();Controls.Add(uninstall);}
 void AddRow(string label,TextBox box,int y){Controls.Add(new Label{Text=label,Location=new Point(40,y+5),Size=new Size(165,30)});box.Location=new Point(215,y);box.Size=new Size(385,34);box.UseSystemPasswordChar=true;Controls.Add(box);}
 void Save(){settings.IdleMinutes=(int)idle.Value;if(newPass.Text!=""){if(newPass.Text.Length<6||newPass.Text!=confirm.Text){MessageBox.Show("새 비밀번호를 6자 이상 동일하게 입력해주세요.");return;}ParentSecurity.SetPassword(settings,newPass.Text);}settings.Save();AppSettings.SetAutoStart(true);DialogResult=DialogResult.OK;Close();}
 void DeleteData(){if(!ParentSecurity.Ask(this,settings,"모든 사용 기록 삭제"))return;if(MessageBox.Show("사용시간 기록을 모두 삭제할까요?","최종 확인",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)==DialogResult.Yes){UsageData.Load().Clear();MessageBox.Show("사용 기록을 삭제했습니다.");}}
 void Uninstall(){if(!ParentSecurity.Ask(this,settings,"PC Check 프로그램 제거"))return;var u=Path.Combine(AppContext.BaseDirectory,"unins000.exe");if(File.Exists(u)){ParentSecurity.LogAttempt("프로그램 제거 실행",true);System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(u,"/PARENTREMOVE=PCCHK-71A9") {UseShellExecute=true});Environment.Exit(0);}else MessageBox.Show("제거 프로그램을 찾지 못했습니다.");}
}
